import type {Game,Player,Question,RoundResult,SubmittedAnswer} from "../types/game.js";import{applyRoundScores,buildRoundResult}from"./ranking.js";
export const QUESTION_DURATION_MS=30_000;export const QUESTIONS_PER_GAME=10;
function currentQuestion(game:Game):Question{const q=game.questions[game.currentQuestionIndex];if(!q)throw new Error("Current question does not exist.");return q;}
export function startGame(game:Game,now=Date.now()):Game{if(game.status!=="LOBBY")throw new Error("Game can only be started from the lobby.");if(game.questions.length!==QUESTIONS_PER_GAME)throw new Error(`A game must contain exactly ${QUESTIONS_PER_GAME} questions.`);return startQuestion({...game,currentQuestionIndex:0},now);}
export function startQuestion(game:Game,now=Date.now()):Game{if(game.currentQuestionIndex<0||game.currentQuestionIndex>=game.questions.length)throw new Error("Question index is out of bounds.");return{...game,status:"QUESTION",questionStartedAt:now,questionEndsAt:now+QUESTION_DURATION_MS};}
export function submitAnswer(game:Game,playerId:string,value:number,now=Date.now()):Game{if(game.status!=="QUESTION")throw new Error("Answers are only accepted while a question is active.");if(!Number.isFinite(value))throw new Error("Answer must be a finite number.");if(game.questionStartedAt===undefined||game.questionEndsAt===undefined)throw new Error("Question timing is not initialized.");if(now>game.questionEndsAt)throw new Error("Answer arrived after the deadline.");if(!game.players.some(p=>p.id===playerId))throw new Error("Unknown player.");const q=currentQuestion(game),existing=game.answersByQuestion.get(q.id)??[];if(existing.some(a=>a.playerId===playerId))throw new Error("Player has already answered this question.");const answer:SubmittedAnswer={playerId,questionId:q.id,value,submittedAt:now,responseTimeMs:now-game.questionStartedAt};const m=new Map(game.answersByQuestion);m.set(q.id,[...existing,answer]);return{...game,answersByQuestion:m};}
export function closeQuestion(game:Game,now=Date.now()):{game:Game;result:RoundResult}{if(game.status!=="QUESTION")throw new Error("Only an active question can be closed.");if(game.questionEndsAt===undefined)throw new Error("Question timing is not initialized.");const q=currentQuestion(game),answers=game.answersByQuestion.get(q.id)??[],allAnswered=game.players.length>0&&answers.length>=game.players.length;if(now<game.questionEndsAt&&!allAnswered)throw new Error("Question cannot be closed before the deadline unless all players have answered.");const result=buildRoundResult(q,game.players,answers);return{game:{...game,status:"ROUND_RESULT",players:applyRoundScores(game.players,result)},result};}
export function showLeaderboard(game:Game):Game{if(game.status!=="ROUND_RESULT")throw new Error("Leaderboard follows the round result.");return{...game,status:"LEADERBOARD"};}
export function nextQuestion(game:Game,now=Date.now()):Game{if(game.status!=="LEADERBOARD")throw new Error("Next question can only start from the leaderboard.");const next=game.currentQuestionIndex+1;if(next>=game.questions.length)return{...game,status:"FINISHED",questionStartedAt:undefined,questionEndsAt:undefined};return startQuestion({...game,currentQuestionIndex:next},now);}
export function addPlayer(game:Game,player:Player):Game{if(game.status!=="LOBBY")throw new Error("Players can only join while the lobby is open.");const n=player.name.trim().toLocaleLowerCase("de");if(game.players.some(p=>p.name.trim().toLocaleLowerCase("de")===n))throw new Error("Player name is already in use.");return{...game,players:[...game.players,player]};}
