"use client";
import{useEffect,useState}from"react";
import{useParams}from"next/navigation";
import{getSocket}from"@/client/socket";
import{Countdown}from"@/components/Countdown";

export default function Host(){
 const{code}=useParams<{code:string}>(),c=code.toUpperCase(),[q,setQ]=useState<any>(),[count,setCount]=useState({count:0,total:0}),[round,setRound]=useState<any>(),[leader,setLeader]=useState<any[]>(),[done,setDone]=useState(false);
 useEffect(()=>{const s=getSocket();const question=(x:any)=>{setQ(x);setRound(null);setLeader(undefined);setCount({count:0,total:0})};s.on("question_started",question);s.on("answer_count_updated",setCount);s.on("round_results",setRound);s.on("leaderboard",(x:any)=>setLeader(x.entries));s.on("game_finished",(x:any)=>{setLeader(x.entries);setDone(true)});return()=>{s.off("question_started",question);s.off("answer_count_updated");s.off("round_results");s.off("leaderboard");s.off("game_finished")}},[]);
 const token=()=>localStorage.getItem(`schaetzspiel:host:${c}`);
 const vals=round?.rankedAnswers?.map((x:any)=>x.value)??[];const best=round?.rankedAnswers?.[0];const min=vals.length?Math.min(...vals):null,max=vals.length?Math.max(...vals):null;
 return <main className="page"><section className="shell host-shell">{done?<><div className="kicker">Endergebnis</div><h1 className="brand">Finale 🏆</h1><Board rows={leader}/></>:leader?<><div className="kicker">Gesamtwertung</div><h1 className="brand">Rangliste</h1><Board rows={leader}/><button className="button" onClick={()=>getSocket().emit("next_question",{joinCode:c,hostToken:token()})}>Nächste Frage</button></>:round?<><div className="kicker">Rundenergebnis</div><h1 className="brand">Auflösung</h1><div className="host-grid"><Board rows={round.rankedAnswers?.map((x:any)=>({rank:x.rank,name:x.playerName,totalScore:`+${x.points}`}))}/><aside className="stack"><div className="card stack"><div className="label">Richtige Antwort</div><div className="stat-value">{round.correctAnswer} {q?.question?.unit??""}</div></div>{best&&<div className="card stack"><div className="label">Bester Tipp</div><div className="stat-value">{best.playerName}</div><div>{best.value} {q?.question?.unit??""}</div></div>}{min!==null&&max!==null&&<div className="card stack"><div className="label">Spannweite</div><div className="stat-value">{min} – {max}</div></div>}<button className="button" onClick={()=>getSocket().emit("show_leaderboard",{joinCode:c,hostToken:token()})}>Gesamtrangliste</button></aside></div></>:q?<div className="host-grid"><div className="card stack"><div className="kicker">Frage {q.questionNumber} / {q.totalQuestions}</div><div className="question">{q.question.text}</div></div><div className="card stack"><Countdown endsAt={q.questionEndsAt}/><div className="stat-value">{count.count} / {count.total}</div><div className="muted">Antworten abgegeben</div></div></div>:<div className="card">Warte auf Spielstart…</div>}</section></main>
}
function Board({rows=[]}:{rows?:any[]}){return <div className="card leader">{rows?.map((x:any)=><div className="row" key={x.id??x.name}><b>{x.rank}.</b><span>{x.name}</span><b>{x.totalScore}</b></div>)}</div>}
