"use client";
import{useEffect,useState}from"react";
import{useParams}from"next/navigation";
import{getSocket}from"@/client/socket";
import{Countdown}from"@/components/Countdown";

export default function Host(){
 const{code}=useParams<{code:string}>(),c=code.toUpperCase(),[q,setQ]=useState<any>(),[count,setCount]=useState({count:0,total:0}),[round,setRound]=useState<any>(),[leader,setLeader]=useState<any[]>(),[done,setDone]=useState(false),[error,setError]=useState("");
 useEffect(()=>{const s=getSocket();const question=(x:any)=>{setQ(x);setRound(null);setLeader(undefined);setCount({count:0,total:0});setError("")};s.on("question_started",question);s.on("answer_count_updated",setCount);s.on("round_results",setRound);s.on("leaderboard",(x:any)=>setLeader(x.entries));s.on("game_finished",(x:any)=>{setLeader(x.entries);setDone(true)});return()=>{s.off("question_started",question);s.off("answer_count_updated");s.off("round_results");s.off("leaderboard");s.off("game_finished")}},[]);
 const token=()=>localStorage.getItem(`schaetzspiel:host:${c}`);
 const evaluate=()=>getSocket().emit("evaluate_round",{joinCode:c,hostToken:token()},(x:any)=>{if(!x.ok)setError(x.message??"Auswertung konnte nicht gestartet werden.")});
 const vals=round?.rankedAnswers?.map((x:any)=>x.value)??[];const best=round?.rankedAnswers?.[0];const min=vals.length?Math.min(...vals):null,max=vals.length?Math.max(...vals):null;const allAnswered=count.total>0&&count.count>=count.total;const progress=count.total?Math.min(100,count.count/count.total*100):0;const unit=q?.question?.unit??"";
 return <main className="page"><section className="shell host-shell">{done?<><div className="kicker">Endergebnis</div><h1 className="brand">Finale 🏆</h1><Board rows={leader}/><div className="actions"><a className="button" href="/create">Neues Spiel</a><a className="button secondary" href="/">Zur Startseite</a></div></>:leader?<><div className="kicker">Gesamtwertung</div><h1 className="brand">Rangliste</h1><Board rows={leader}/><button className="button" onClick={()=>getSocket().emit("next_question",{joinCode:c,hostToken:token()})}>Nächste Frage</button></>:round?<div className="sports-results"><div className="score-head"><div><span className="score-badge">Ergebnis</span><div className="score-title">Runde {q?.questionNumber??""} ausgewertet</div></div><div className="kicker">Schätzspiel</div></div><div className="sports-stats"><Stat label="Richtige Antwort" value={`${round.correctAnswer} ${unit}`}/>{best&&<Stat label="Bester Tipp" value={`${best.value} ${unit}`} sub={best.playerName}/>} {min!==null&&max!==null&&<Stat label="Tipp-Spannweite" value={`${min} – ${max}`} sub={unit}/>}</div><div className="host-grid" style={{marginTop:18}}><Board rows={round.rankedAnswers?.map((x:any)=>({rank:x.rank,name:x.playerName,totalScore:`+${x.points}`}))}/><aside className="stack"><div className="card stack"><div className="label">Die Frage</div><div style={{fontWeight:900,fontSize:"1.25rem"}}>{q?.question?.text}</div>{round.explanation&&<div className="sports-sub">{round.explanation}</div>}</div><button className="button" onClick={()=>getSocket().emit("show_leaderboard",{joinCode:c,hostToken:token()})}>Gesamtrangliste →</button></aside></div></div>:q?<div className="host-grid"><div className="card stack"><div className="kicker">Frage {q.questionNumber} / {q.totalQuestions}</div><div className="question">{q.question.text}</div></div><div className="card stack"><Countdown endsAt={q.questionEndsAt}/><div><div className="stat-value">{count.count} / {count.total}</div><div className="muted">Antworten abgegeben</div></div><div className="answer-progress"><span style={{width:`${progress}%`}}/></div>{allAnswered&&<button className="button" onClick={evaluate}>Auswertung starten →</button>}{error&&<div className="error">{error}</div>}</div></div>:<div className="card">Warte auf Spielstart…</div>}</section></main>
}
function Stat({label,value,sub}:{label:string,value:string,sub?:string}){return <div className="sports-stat"><div className="label">{label}</div><div className="stat-value">{value}</div>{sub&&<div className="sports-sub">{sub}</div>}</div>}
function Board({rows=[]}:{rows?:any[]}){return <div className="card leader">{rows?.map((x:any)=><div className="row" key={x.id??x.name}><b>{x.rank}.</b><span>{x.name}</span><b>{x.totalScore}</b></div>)}</div>}
